// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://giqaiazucvttddomuquy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdpcWFpYXp1Y3Z0dGRkb211cXV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNjQ4NjksImV4cCI6MjA2MDY0MDg2OX0.R-6YIo9nkbiTCsI5ZwNGWWuBdxhvfAJAeiQaIdIEmZM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);